name: Package Extension

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      # Extension Versioning
      - name: Set manifest version
        run: |
          jq '.+= { "version": "2.4.${{ github.run_number }}" }' manifest.json > tmp.$$.json && mv tmp.$$.json manifest.json
          cat manifest.json
        working-directory: src

      # Build local modules
      - name: 'ğŸšš npm install (libs/roblox)'
        run: npm ci
        working-directory: ./libs/roblox

      - name: 'ğŸ—ï¸ Build libs/roblox'
        run: npm run build
        working-directory: ./libs/roblox

      - name: 'ğŸšš npm install (libs/extension-utils)'
        run: npm ci
        working-directory: ./libs/extension-utils

      - name: 'ğŸ—ï¸ Build libs/extension-utils'
        run: npm run build
        working-directory: ./libs/extension-utils

      - name: 'ğŸšš npm install (libs/extension-messaging)'
        run: npm ci
        working-directory: ./libs/extension-messaging

      - name: 'ğŸ—ï¸ Build libs/extension-messaging'
        run: npm run build
        working-directory: ./libs/extension-messaging

      # Build extension itself
      - name: 'ğŸšš npm install'
        run: npm ci

      - name: bundle react
        run: npm run react

      - name: 'ğŸ—ï¸ Build'
        run: |
          npm run build

      # Attach build artifacts
      - name: Attach build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: src/**
